version: "2"

services:
  sut:
    image: system-under-test
    build: ./system-under-test
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080

  sut-readhook:
    image: system-under-test
    build: ./system-under-test
    ports:
      - "8081:8081"
    environment:
      - LD_PRELOAD=/opt/hook/readhook.so
      - SERVER_PORT=8081
    volumes:
      - ../hook/out:/opt/hook

  locust:
    image: test-bench
    build: ./test-bench
    ports:
      - "8089:8089"
    volumes:
      - ./benchmark_results:/tmp/benchmark_results

  # this is only for building the image
  # with 'docker compose --profile with-readhook build'
  readhook:
    profiles:
      - with-readhook
    image: readhook
    build: ../hook
