# docker-compose.yml
version: '2'

services:
  system-under-test:
    image: benchmark-system-under-test
    build:
      context: ./benchmark/system-under-test
      dockerfile: Dockerfile
  system-under-test-active-ldpreload:
    image: benchmark-system-under-test
    ports:
     - "8081:8080"
    environment:
      - LD_PRELOAD=/opt/readhook.so

  test-bench:
    image: benchmark-test-bench
    build:
      context: ./benchmark/test-bench
      dockerfile: Dockerfile
    ports:
     - "8089:8089"
    volumes:
      - ./jupyter-notebooks/data:/opt/locust/cvs_exports
