apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: function-hook-benchmarking
build:
  artifacts:
    # Building the images with @dockefile within the @context folder
    - image: benchmark-system-under-test
      context: ./src/webhook
      docker:
        dockerfile: ./Dockerfile
  local:
    # only the docker CLI respects a manually logged-in daemon
    useDockerCLI: true
    # BuildKit provides an improvement on performance
    useBuildkit: true
deploy:
  # deploy artifacts using kubectl
  kubectl:
    {}

profiles:
  - name: local-kind
    manifests:
      kustomize:
        paths:
          - ./k8s-manifests/base/namespace.yaml 
          - ./k8s-manifests/base/same-pod/deployment.yaml
