apiVersion: v1
kind: Service
metadata:
  name: benchmark
  labels:
    app.kubernetes.io/name: suite-service
    app.kubernetes.io/part-of: benchmark
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: locust
    app.kubernetes.io/part-of: benchmark
  ports:
    - port: 8089
      targetPort: 8089
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-suite
  labels:
    app.kubernetes.io/name: suite-deployment
    app.kubernetes.io/part-of: benchmark
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: locust
      app.kubernetes.io/part-of: benchmark
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: locust
        app.kubernetes.io/part-of: benchmark
    spec:
      containers:
        - name: backend-without-ldprelaod
          imagePullPolicy: Always
          image: ${REPOSITORY_URL}/benchmark-system-under-test
          ports:
            - containerPort: 8080
        - name: backend-with-ldprelaod
          imagePullPolicy: Always
          image: ${REPOSITORY_URL}/benchmark-system-under-test
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: LD_PRELOAD
              value: "/opt/ldpreload.so"
        - name: benchmark-test-bench
          imagePullPolicy: Always
          image: ${REPOSITORY_URL}/benchmark-test-bench
          ports:
            - containerPort: 8089
