apiVersion: v1
kind: Service
metadata:
  name: benchmark-sut-nodes
  labels:
    app.kubernetes.io/name: sut-service-node
    app.kubernetes.io/part-of: benchmark
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sut-node
    app.kubernetes.io/part-of: benchmark
  ports:
    - name: without-ldpreload
      port: 8080
      targetPort: 8080
    - name: with-ldpreload
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-sut-nodes
  labels:
    app.kubernetes.io/name: sut-node
    app.kubernetes.io/part-of: benchmark
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sut-node
      app.kubernetes.io/part-of: benchmark
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sut-node
        app.kubernetes.io/part-of: benchmark
    spec:
      containers:
        - name: node-backend-without-ldprelaod
          imagePullPolicy: Always
          image: ${REPOSITORY_URL}/benchmark-system-under-test
          ports:
            - containerPort: 8080
        - name: node-backend-with-ldprelaod
          imagePullPolicy: Always
          image: ${REPOSITORY_URL}/benchmark-system-under-test
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: LD_PRELOAD
              value: "/opt/readhook.so"
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - ${HOSTNAME}
