apiVersion: v1
kind: Service
metadata:
  name: benchmark-test-bench-nodes
  labels:
    app.kubernetes.io/name: tb-service-node
    app.kubernetes.io/part-of: benchmark
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tb-node
    app.kubernetes.io/part-of: benchmark
  ports:
    - port: 8089
      targetPort: 8089
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-tb
  labels:
    app.kubernetes.io/name: tb-node
    app.kubernetes.io/part-of: benchmark
spec:   
  selector:
    matchLabels:
      app.kubernetes.io/name: tb-node
      app.kubernetes.io/part-of: benchmark
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tb-node
        app.kubernetes.io/part-of: benchmark
    spec:
      containers:            
        - name: benchmark-test-bench
          imagePullPolicy: Always
          image: ${REPOSITORY_URL}/benchmark-test-bench
          ports:
            - containerPort: 8089
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - ${HOSTNAME} 