// Copyright 2023 Dynatrace LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Portions of this code, as identified in remarks, are provided under the
// Creative Commons BY-SA 4.0 or the MIT license, and are provided without
// any warranty. In each of the remarks, we have provided attribution to the
// original creators and other attribution parties, along with the title of
// the code (if known) a copyright notice and a link to the license, and a
// statement indicating whether or not we have modified the code.

#include "main.h"

unsigned char SOCKET_PORT_MAPPING[MAX_SOCKET_FD] = {SOCKET_FD_UNTRACEABLE};

/**
 * @brief A selection of keywords to block, taken from the first few entries of
 * https://github.com/danielmiessler/SecLists/blob/master/Discovery/Web-Content/raft-medium-words-lowercase.txt
 */
const char* WORD_LIST[] = {
        ".php",
        "cgi-bin",
        "images",
        "admin",
        "includes",
        "search",
        ".html",
        "cache",
        "login",
        "modules",
        "templates",
        "plugins",
        "wp-admin",
        "themes",
        "js",
        "index",
        "xmlrpc",
        "wp-includes",
        "media",
        "wp-content",
        "css",
        "language",
        "tmp",
        "scripts",
        "register",
        "misc",
        "install",
        "administrator",
        "cron",
        "feed",
        "user",
        "components",
        "bin",
        "trackback",
        "installation",
        "contact",
        ".txt",
        ".htm",
        ".aspx",
        "libraries",
        "stats",
        "forum",
        "test",
        ".asp",
        "download",
        ".css",
        "comments",
        ".js",
        "profile",
        "private",
        "include",
        "category",
        "logout",
        "comment",
        "report",
        "tag",
        "member",
        "add",
        "update",
        "img",
        "password",
        "calendar",
        "rss",
        "license",
        "memberlist",
        "profiles",
        "reply",
        "node",
        "ajax",
        "files",
        "changelog",
        "upgrade",
        ".mysql",
        ".pgsql",
        ".pgsql.txt",
        ".mysql.txt",
        "maintainers",
        "image",
        "account",
        "logs",
        "data",
        "faq",
        "blog",
        "cart",
        ".inc",
        "help",
        "temp",
        "newreply",
        "sites",
        "newthread",
        "objects",
        "dyn",
        "config",
        ".pdf",
        "usercp",
        "_private",
        "inc",
        "page",
        "online",
        "news",
        "aspnet_client",
        "editpost",
        "sendmessage",
        "wp-login",
        "subscription",
        "lib",
        "go",
        "author",
        ".cgi",
        "attachment",
        "poll",
        "uploads",
        "threadrate",
        "printthread",
        "error",
        "catalog",
        "modcp",
        "checkout",
        ".gif",
        "flash",
        "404",
        ".jpg",
        "docs",
        "moderator",
        "showgroups",
        "joinrequests",
        "members",
        "privacy",
        "postings",
        "backup",
        "reputation",
        "global",
        "editor",
        "print",
        "downloads",
        "content",
        "links",
        "home",
        "admincp",
        "newsletter",
        "upload",
        "api",
        "en",
        ".swf",
        "common",
        "styles",
        "pdf",
        "email",
        "template",
        "usernote",
        "archive",
        ".xml",
        "forums",
        "redirect",
        "gallery",
        "newattachment",
        "inlinemod",
        "create_account",
        "db",
        "shop",
        "ads",
        "assets",
        "shopping_cart",
        "view",
        "wp-register",
        "tools",
        "tags",
        "about",
        "pub",
        "statistics",
        ".cfm",
        "recommend",
        "order",
        "posting",
        "archives",
        "mambots",
        "database",
        "style",
        "sitemap",
        "_notes",
        "mail",
        "_vti_cnf",
        "popup_image",
        "banners",
        "classes",
        "advanced_search",
        "_vti_log",
        "customavatars",
        "product",
        "pages",
        "_vti_pvt",
        "clientscript",
        "customer",
        "video",
        "store",
        "contact_us",
        "app",
        ".xhtml",
        "users",
        "engine"};
